---
version: 2

# changelog
changelog:
  use: "git"
  sort: "desc"
  filters:
    exclude:
      - "^chore"
      - "^ci"
      - "^docs"
  groups:
    - title: "🚀 Features"
      regexp: "^feat"
    - title: "🐛 Bug Fixes"
      regexp: "^fix"
    - title: "🛠 Maintenance"
      regexp: "^(chore|refactor)"

# gitlab
gitlab_urls:
  api: "https://gitlab.simoncor.net/api/v4/"
  download: "https://gitlab.simoncor.net"
  use_package_registry: true
